### ISSUE TITLE
Ajax adtocart

### ISSUE THREAD

**Issue by Danieleeffe1** [OpenMage/documentation#4]
https://github.com/omnipartners/m1-ajax-add-to-cart

of all the modules I have tried this is the simplest they all have the same problem (this module too) if a configurable product is inserted in the cart (qty1) the system enters qty2

Live demo bug
https://openmage.vetrinadigitale.eu/saldi/adesivo02-saldi-sconti-xx.html

**Comment by fballiano** [comment]
it the demo working? it redirects me to the cart page

**Comment by Danieleeffe1** [comment]
https://test.monsterbox.it/promo.html

do more tests

Il gio 6 mag 2021, 22:32 Fabrizio Balliano ***@***.***> ha
scritto:

**Comment by fballiano** [comment]
:-D this link works, the other one no...

**Comment by fballiano** [comment]
another one to check: https://github.com/proatwork/ajaxstuff

**Comment by Danieleeffe1** [comment]
Try to put a product in the cart

Il gio 6 mag 2021, 22:42 Fabrizio Balliano ***@***.***> ha
scritto:

**Comment by fballiano** [comment]
> Try to put a product in the cart Il gio 6 mag 2021, 22:42 Fabrizio Balliano ***@***.***> ha scritto:

WTH obviously! on the first link you posted it doesn't work!

**Comment by Danieleeffe1** [comment]
Thanks Fabrizio

I had already downloaded but the "basic settings"
to me they are not clear and therefore I don't know how to use it.

If we want to integrate it on the theme "RWDLUMA" modified by me I must first understand if it works.

If you are Italian please write to me in that language thank you.

**Comment by sreichel** [comment]
@fballiano close?
