### ISSUE TITLE
Webp image

### ISSUE THREAD

**Issue by Danieleeffe1** [OpenMage/documentation#5]
[Yireo_Webp-master.zip](https://github.com/OpenMage/documentation/files/6409077/Yireo_Webp-master.zip)

this module enables the conversion of images in the webp format ,tested on openmage .

conflict with infinityscroll: 
it does not load the thumbnails of the products in the following pages of the categories)

**Comment by fballiano** [comment]
I think it's actually better to link the repo: https://github.com/yireo-magento1/Yireo_Webp
