### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by Danieleeffe1** [OpenMage/documentation#6]
great module for infinite scrolling of products in categories. 

all information on the module can be found here

[https://github.com/meanbee/magento-infinite-scroll.git](https://github.com/meanbee/magento-infinite-scroll.git)

[magento-infinite-scroll-develop.zip](https://github.com/OpenMage/documentation/files/6409087/magento-infinite-scroll-develop.zip)

**Comment by ADDISON74** [comment]
This post is not related to the repository and it should be closed. It can be posted in the Discussions section of the OpenMage/magento-lts repository.

BTW, some of us should also get rights for some repositories like this one or Web_Notifications.

**Comment by Flyingmana** [comment]
its on the list to get added to our documentation in the 3th party modules section https://openmage.readthedocs.io/en/latest/modules/index.html
